<a href="https://colab.research.google.com/github/yashsinghal11/Pytorch-Full-Tutorial-Theory-/blob/main/creating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating tensors

method1. creating tensor using empty

In [4]:
import torch
a=torch.empty([2,3])
print(a)

'''It creates tensor as empty space and did'nt assign any values just to create tensor memory'''

tensor([[0.0606, 0.0000, 0.0606],
        [0.0000, 0.0000, 0.0000]])


"It creates tensor as empty space and did'nt assign any values just to create tensor memory"

method 2. using zeroes

In [10]:
b=torch.zeros([2,3])
print(b)
'''create a tensor with all values a s0'''

tensor([[0., 0., 0.],
        [0., 0., 0.]])


method3. using ones

In [12]:
c=torch.ones([2,3])
print(c)

'''create a tensor of all values as 1'''

tensor([[1., 1., 1.],
        [1., 1., 1.]])


'create a tensor of all values as 1'

method 4 : using random

In [16]:
d=torch.rand([2,3])
print(d)

'''create tensor with randome values between 0 and 1'''

tensor([[0.0851, 0.0644, 0.0803],
        [0.8777, 0.8699, 0.1136]])


'create tensor with randome values between 0 and 1'

method 5: using mannual seed if want to use the randome tensor again and again

In [21]:
torch.manual_seed(100)
e=torch.rand([2,3])
print(e)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


method 6 using tensor to customise and make own tensors

In [23]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

method 7 using arang,linespace.eye

In [25]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [29]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])