<a href="https://colab.research.google.com/github/yashsinghal11/Pytorch-Full-Tutorial-Theory-/blob/main/Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [44]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [45]:
df.drop(columns=["id","Unnamed: 32"], inplace=True)

In [28]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [46]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [47]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [49]:
x_train

array([[ 1.01870393, -1.01122197,  0.99148954, ...,  0.49364216,
        -0.20523354, -0.25856669],
       [ 0.86124359,  1.08912797,  0.90002607, ...,  1.0845638 ,
         1.0680351 ,  0.05224162],
       [ 0.58926663,  0.07070521,  0.53832964, ...,  0.59036591,
        -0.37960883, -1.10431861],
       ...,
       [ 0.29438635, -0.61373133,  0.31507564, ..., -0.16831098,
        -1.15771744,  0.08922946],
       [-0.95957058, -0.98770182, -0.98370555, ..., -1.70682307,
        -0.28090583, -1.22742741],
       [-0.77348108, -0.07276774, -0.80452031, ..., -0.65480119,
        -0.79087131, -0.96409604]])

In [50]:
x_test

array([[-0.32237682,  0.12957744, -0.37740747, ..., -0.08333652,
        -0.14826128, -0.59235787],
       [ 1.34996787, -0.05176813,  1.32068292, ...,  1.34003368,
         0.43821182,  0.32964071],
       [-0.96237562,  0.75868986, -0.95401885, ..., -0.90367222,
         0.28929064, -0.22029373],
       ...,
       [-1.11820141, -0.16370984, -1.14166868, ..., -1.56648828,
        -0.43228622, -0.94978711],
       [-0.43368096, -0.1413215 , -0.50719525, ..., -1.12508536,
        -1.52539839, -1.26894046],
       [ 0.32318719,  0.03778524,  0.47686139, ...,  1.45864787,
         1.94124106,  1.16889582]])

In [51]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [52]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,

In [53]:
y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1])

In [54]:
x_train_tensor=torch.from_numpy(x_train)
y_train_tensor=torch.from_numpy(y_train)
x_test_tensor=torch.from_numpy(x_test)
y_test_tensor=torch.from_numpy(y_test)

In [55]:
x_train_tensor.shape

torch.Size([455, 30])

In [56]:
y_train_tensor.shape

torch.Size([455])

In [65]:
class mysimplenn():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
  def losscalculate(self, y_pred, y):
        epsilon = 1e-7

        # ✅ Correct clamp usage: clamp(tensor, min, max)
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # ✅ Use y (not y_train_tensor)
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [66]:
learning_rate=0.1
epochs=25


In [67]:
# create model
model = mysimplenn(x_train_tensor)

# training loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(x_train_tensor)

    # loss calculate
    loss = model.losscalculate(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.898837890146187
Epoch: 2, Loss: 3.7857624769156586
Epoch: 3, Loss: 3.6687818716919707
Epoch: 4, Loss: 3.54864430317248
Epoch: 5, Loss: 3.4254627617107007
Epoch: 6, Loss: 3.2941660855687362
Epoch: 7, Loss: 3.155776875440933
Epoch: 8, Loss: 3.0056447551814824
Epoch: 9, Loss: 2.84669982068314
Epoch: 10, Loss: 2.6841332898978814
Epoch: 11, Loss: 2.5142894145774033
Epoch: 12, Loss: 2.335601476312227
Epoch: 13, Loss: 2.1526004616904535
Epoch: 14, Loss: 1.9695892263843686
Epoch: 15, Loss: 1.7935733086495935
Epoch: 16, Loss: 1.6233990144115409
Epoch: 17, Loss: 1.4610131691701795
Epoch: 18, Loss: 1.3120651825812586
Epoch: 19, Loss: 1.1790776146084008
Epoch: 20, Loss: 1.0644225803474565
Epoch: 21, Loss: 0.9698913213653431
Epoch: 22, Loss: 0.8961279667316527
Epoch: 23, Loss: 0.8420927461274096
Epoch: 24, Loss: 0.8049259365237268
Epoch: 25, Loss: 0.7804659993116829


In [68]:
model.bias

tensor([-0.1251], dtype=torch.float64, requires_grad=True)

In [69]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5831024646759033
